# Generated by Django 3.2.13 on 2022-08-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abs_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_dans_la_base', models.PositiveSmallIntegerField(default=0)),
                ('repos', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ADC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ADC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contributeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_contributeur', models.CharField(max_length=50)),
                ('prenom_contributeur', models.CharField(max_length=100)),
                ('email_contributeur', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exclu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additif_rectificatif_erratum_modif', models.PositiveSmallIntegerField(default=0)),
                ('doublon', models.PositiveSmallIntegerField(default=0)),
                ('exclu_ceremonie', models.PositiveSmallIntegerField(default=0)),
                ('aucun_ville', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.PositiveSmallIntegerField()),
                ('nom_journal', models.CharField(max_length=50)),
                ('nombre_de_page', models.PositiveSmallIntegerField()),
                ('nombre_ADC', models.PositiveSmallIntegerField(default=0)),
                ('date_heure_debut', models.DateTimeField(auto_now_add=True)),
                ('heure_fin', models.TimeField()),
                ('observation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tache', models.CharField(max_length=50)),
                ('date_heure_debut_tache', models.DateTimeField(auto_now_add=True)),
                ('heure_fin_tache', models.TimeField()),
                ('observation_tache', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
