# Generated by Django 3.2.13 on 2022-08-23 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_journalname'),
        ('contributeur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abs_base',
            name='adc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contributeur.adc'),
        ),
        migrations.AddField(
            model_name='adc',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contributeur.journal'),
        ),
        migrations.AddField(
            model_name='contributeur',
            name='action_contributeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.action'),
        ),
        migrations.AddField(
            model_name='exclu',
            name='adc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contributeur.adc'),
        ),
        migrations.AddField(
            model_name='journal',
            name='contributeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contributeur.contributeur'),
        ),
        migrations.AddField(
            model_name='journal',
            name='statut_journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.statutjournal'),
        ),
        migrations.AddField(
            model_name='tache',
            name='contributeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contributeur.contributeur'),
        ),
        migrations.AddField(
            model_name='tache',
            name='statut_tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.statuttache'),
        ),
        migrations.AlterField(
            model_name='contributeur',
            name='email_contributeur',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contributeur',
            name='nom_contributeur',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contributeur',
            name='prenom_contributeur',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='journal',
            name='nom_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.journalname'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='nom_tache',
            field=models.CharField(max_length=30),
        ),
    ]
