# Generated by Django 3.2.13 on 2022-08-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributeur', '0002_auto_20220823_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='edition',
        ),
    ]
