# Generated by Django 3.2.13 on 2022-09-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributeur', '0003_remove_journal_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributeur',
            name='have_account',
            field=models.BooleanField(default=False),
        ),
    ]
