# Generated by Django 3.2.13 on 2022-09-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributeur', '0004_contributeur_have_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adc',
            old_name='nom_ADC',
            new_name='reference_ADC',
        ),
    ]
