# Generated by Django 3.2.13 on 2022-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributeur', '0005_rename_nom_adc_adc_reference_adc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='heure_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='nombre_ADC',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='nombre_de_page',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
