# Generated by Django 3.2.13 on 2022-09-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_journalname'),
        ('contributeur', '0006_auto_20220921_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='nom_journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.journalname'),
        ),
    ]
