# Generated by Django 3.2.13 on 2022-09-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributeur', '0007_alter_journal_nom_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='jalon',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
