# Generated by Django 3.2.13 on 2022-09-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributeur', '0008_journal_jalon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='jalon',
            field=models.BooleanField(default=False),
        ),
    ]
