# Generated by Django 3.2.13 on 2022-09-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributeur', '0009_alter_journal_jalon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adc',
            name='reference_ADC',
            field=models.CharField(max_length=100),
        ),
    ]
