# Generated by Django 3.2.13 on 2022-08-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_action_statutjournal_statuttache'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_journal', models.CharField(max_length=50)),
            ],
        ),
    ]
