# Generated by Django 3.2.13 on 2022-09-10 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributeur', '0003_remove_journal_edition'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contributeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contributeur.contributeur'),
        ),
    ]
